version: 2
mergeable:
  - when: pull_request.opened
    name: "Greet a contributor"
    validate: []
    pass:
      - do: comment
        payload:
          body: Thanks for creating a pull request! A maintainer will review your changes shortly. Please don't be discouraged if it takes a while.
  - when: pull_request.*
    validate:
      - do: title
        must_exclude:
          regex: ^\[WIP\]
      - do: label
        must_exclude:
          regex: 'wip'
      - do: description
        no_empty:
          enabled: true
          message: Description matter and should not be empty. Provide detail with **what** was changed, **why** it was changed, and **how** it was changed.
  - when: pull_request.*, pull_request_review.*
    name: 'Approvals check'
    validate:
      - do: approvals
        required:
          owners: true
          assignees: true
          requested_reviewers: true
  - when: issues.opened
    validate:
      - do: title
        begins_with:
          match: ['DESKTOP', 'CORE']
      - do: label
        must_include:
          regex: bug|enhancement|suggestion
    fail:
      - do: comment
        payload:
          body: >
            The following problems were found with this issue:
              - Title must begin with `CORE` or `DESKTOP`
              - The issue should either be labeled `bug`, `enhancement` or `suggestion`
