[versions]
androidx-lifecycle = "2.9.4"
composeHotReload = "1.0.0-beta07"
composeMultiplatform = "1.9.0"
kotlin = "2.2.20"
lib-kotlinx-serialization = "1.9.0"
plugin-kotlinx-serialization = "2.2.0"
detekt = "1.23.8"
exposed = "1.0.0-rc-1"
h2 = "2.3.232"
junit5 = "5.13.4"
phonenumber = "9.0.14"
javamoney = "1.4.5"
icerock-resources = "0.25.0"
navigation = "2.9.0"
kermit = "2.0.8"
appdirs = "2.0.0"
kotlinx-coroutines = "1.10.2"

[libraries]
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
icerock-resources = { module = "dev.icerock.moko:resources", version.ref = "icerock-resources" }
icerock-resources-compose = { module = "dev.icerock.moko:resources-compose", version.ref = "icerock-resources" }
jetbrains-androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation" }
jetbrains-kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "lib-kotlinx-serialization" }
jetbrains-exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
jetbrains-exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
jetbrains-exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
jetbrains-exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
jetbrains-exposed-money = { module = "org.jetbrains.exposed:exposed-money", version.ref = "exposed" }
java-money = { module = "org.javamoney:moneta", version.ref = "javamoney" }
database-h2 = { module = "com.h2database:h2", version.ref = "h2" }
touchlab-kermit = { module = "co.touchlab:kermit", version.ref = "kermit"}
gosyer-appdirs = { module = "ca.gosyer:kotlin-multiplatform-appdirs", version.ref = "appdirs" }
google-libs-phonenumber = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "phonenumber" }
tests-androidx-navigation = { module = "androidx.navigation:navigation-testing", version.ref = "navigation" }
tests-jetbrains-kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
tests-jetbrains-kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
tests-junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5"}
tests-junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5"}
tests-junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5"}
tests-icerock-resources = { module = "dev.icerock.moko:resources-test", version.ref = "icerock-resources" }

[plugins]
icerock-resources-multiplatform = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "icerock-resources" }
jetbrains-kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "plugin-kotlinx-serialization" }
jetbrains-compose-hotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
jetbrains-compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
jetbrains-kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
arturbosch-detekt = { id = "io.gitlab.arturbosch.detekt",  version.ref = "detekt" }
